-- 046_instance_pages_drop_builtin.sql — purge legacy `kind = 'builtin'`
-- instance-page rows.
--
-- The built-in instance sub-pages (Home / Files / Network / Terminal / Env /
-- Automation / Processes / Metrics / Ports / Backups / Audit / Settings) were
-- CONVERTED to fully self-contained custom pages in the Instance Pages
-- library (instance_pages/pages/*.json, all `kind: "custom"`,
-- `content_type: "html"`). The frontend no longer ships any built-in page
-- components, so a `kind = 'builtin'` row is dead weight: it renders nothing
-- in the instance panel and shows up as an un-importable "Built-in" entry on
-- the Instance Pages admin page.
--
-- This migration deletes every such row so the library only lists real,
-- importable custom pages. Plain ANSI SQL — identical on MySQL, PostgreSQL
-- and SQLite, and naturally idempotent when migrations re-run each launch
-- (deleting zero rows succeeds).
--
-- Re-creation is blocked at the API layer: validateInstancePage now rejects
-- kind='builtin' on create/update/import.

DELETE FROM instance_pages WHERE kind = 'builtin';
