-- 054_notifications_media.sql: rich notification detail with media support.
--
-- Adds per-notification rich fields so the detail page and dropdown can show
-- name + notes + complete detail and render images / videos / gifs:
--   notes       TEXT — extra free-form notes (markdown-ish)
--   cover_image TEXT — primary image / gif / video poster URL
--   media_json  TEXT — JSON array [{type,url}] for gallery
-- This migration is handled via Go guardedAddColumns (see db.go) for MySQL/SQLite
-- idempotency; Postgres uses ADD COLUMN IF NOT EXISTS natively.

-- handled in Go via guardedAddColumns — no raw ALTER here for SQLite
