// Static ISO-3166 country list used by the LocationField picker.
//
// Each row carries the ISO-3166 alpha-2 code the panel persists, the
// flag emoji the picker renders, the English display name, and a small
// keyword bag so users can search by common alternative names ("USA",
// "United States", "America", …). The keyword field is matched
// case-insensitively against the full label in SearchableSelect.
//
// We keep the data inline rather than pulling a runtime dependency — the
// list is static, the file is small once minified, and dropping the dep
// keeps the panel's npm footprint flat. Codes are the key (search: Set
// lookup), not array indices.
export interface CountryRow {
  code: string;
  flag: string;
  name: string;
  keywords?: string;
}

export const COUNTRIES: CountryRow[] = [
  { code: 'AF', flag: '🇦🇫', name: 'Afghanistan', keywords: 'afghan afghanistan' },
  { code: 'AL', flag: '🇦🇱', name: 'Albania', keywords: 'albania albanian' },
  { code: 'DZ', flag: '🇩🇿', name: 'Algeria', keywords: 'algeria dzayer' },
  { code: 'AS', flag: '🇦🇸', name: 'American Samoa', keywords: 'american samoa' },
  { code: 'AD', flag: '🇦🇩', name: 'Andorra', keywords: 'andorra' },
  { code: 'AO', flag: '🇦🇴', name: 'Angola', keywords: 'angola' },
  { code: 'AI', flag: '🇦🇮', name: 'Anguilla', keywords: 'anguilla' },
  { code: 'AQ', flag: '🇦🇶', name: 'Antarctica', keywords: 'antarctica south pole' },
  { code: 'AG', flag: '🇦🇬', name: 'Antigua and Barbuda', keywords: 'antigua barbuda' },
  { code: 'AR', flag: '🇦🇷', name: 'Argentina', keywords: 'argentina argentinian' },
  { code: 'AM', flag: '🇦🇲', name: 'Armenia', keywords: 'armenia armenian' },
  { code: 'AW', flag: '🇦🇼', name: 'Aruba', keywords: 'aruba' },
  { code: 'AU', flag: '🇦🇺', name: 'Australia', keywords: 'australia aussie oz' },
  { code: 'AT', flag: '🇦🇹', name: 'Austria', keywords: 'austria austrian osterreich' },
  { code: 'AZ', flag: '🇦🇿', name: 'Azerbaijan', keywords: 'azerbaijan azeri' },
  { code: 'BS', flag: '🇧🇸', name: 'Bahamas', keywords: 'bahamas' },
  { code: 'BH', flag: '🇧🇭', name: 'Bahrain', keywords: 'bahrain' },
  { code: 'BD', flag: '🇧🇩', name: 'Bangladesh', keywords: 'bangladesh' },
  { code: 'BB', flag: '🇧🇧', name: 'Barbados', keywords: 'barbados' },
  { code: 'BY', flag: '🇧🇾', name: 'Belarus', keywords: 'belarus byelorussia' },
  { code: 'BE', flag: '🇧🇪', name: 'Belgium', keywords: 'belgium belgian' },
  { code: 'BZ', flag: '🇧🇿', name: 'Belize', keywords: 'belize' },
  { code: 'BJ', flag: '🇧🇯', name: 'Benin', keywords: 'benin dahomey' },
  { code: 'BT', flag: '🇧🇹', name: 'Bhutan', keywords: 'bhutan' },
  { code: 'BO', flag: '🇧🇴', name: 'Bolivia', keywords: 'bolivia bolivian' },
  { code: 'BA', flag: '🇧🇦', name: 'Bosnia and Herzegovina', keywords: 'bosnia herzegovina bih' },
  { code: 'BW', flag: '🇧🇼', name: 'Botswana', keywords: 'botswana' },
  { code: 'BR', flag: '🇧🇷', name: 'Brazil', keywords: 'brazil brazilian brasil' },
  { code: 'IO', flag: '🇮🇴', name: 'British Indian Ocean Territory', keywords: 'biot chagos' },
  { code: 'BN', flag: '🇧🇳', name: 'Brunei', keywords: 'brunei' },
  { code: 'BG', flag: '🇧🇬', name: 'Bulgaria', keywords: 'bulgaria bulgarian' },
  { code: 'BF', flag: '🇧🇫', name: 'Burkina Faso', keywords: 'burkina faso' },
  { code: 'BI', flag: '🇧🇮', name: 'Burundi', keywords: 'burundi' },
  { code: 'KH', flag: '🇰🇭', name: 'Cambodia', keywords: 'cambodia khmer' },
  { code: 'CM', flag: '🇨🇲', name: 'Cameroon', keywords: 'cameroon' },
  { code: 'CA', flag: '🇨🇦', name: 'Canada', keywords: 'canada canadian' },
  { code: 'CV', flag: '🇨🇻', name: 'Cape Verde', keywords: 'cabo verde cape verde' },
  { code: 'KY', flag: '🇰🇾', name: 'Cayman Islands', keywords: 'cayman' },
  { code: 'CF', flag: '🇨🇫', name: 'Central African Republic', keywords: 'car central african' },
  { code: 'TD', flag: '🇹🇩', name: 'Chad', keywords: 'chad' },
  { code: 'CL', flag: '🇨🇱', name: 'Chile', keywords: 'chile chilean' },
  { code: 'CN', flag: '🇨🇳', name: 'China', keywords: 'china chinese prc mainland' },
  { code: 'CO', flag: '🇨🇴', name: 'Colombia', keywords: 'colombia colombian' },
  { code: 'KM', flag: '🇰🇲', name: 'Comoros', keywords: 'comoros' },
  { code: 'CG', flag: '🇨🇬', name: 'Congo (Brazzaville)', keywords: 'congo brazzaville' },
  { code: 'CD', flag: '🇨🇩', name: 'Congo (Kinshasa)', keywords: 'congo kinshasa drc' },
  { code: 'CR', flag: '🇨🇷', name: 'Costa Rica', keywords: 'costa rica' },
  { code: 'CI', flag: '🇨🇮', name: "Côte d\u2019Ivoire", keywords: 'ivory coast cote divoire' },
  { code: 'HR', flag: '🇭🇷', name: 'Croatia', keywords: 'croatia croatian hrvatska' },
  { code: 'CU', flag: '🇨🇺', name: 'Cuba', keywords: 'cuba cuban' },
  { code: 'CY', flag: '🇨🇾', name: 'Cyprus', keywords: 'cyprus cypriot' },
  { code: 'CZ', flag: '🇨🇿', name: 'Czechia', keywords: 'czechia czech republic cesky' },
  { code: 'DK', flag: '🇩🇰', name: 'Denmark', keywords: 'denmark danish danmark' },
  { code: 'DJ', flag: '🇩🇯', name: 'Djibouti', keywords: 'djibouti' },
  { code: 'DM', flag: '🇩🇲', name: 'Dominica', keywords: 'dominica' },
  { code: 'DO', flag: '🇩🇴', name: 'Dominican Republic', keywords: 'dominican republic dr' },
  { code: 'EC', flag: '🇪🇨', name: 'Ecuador', keywords: 'ecuador' },
  { code: 'EG', flag: '🇪🇬', name: 'Egypt', keywords: 'egypt egyptian' },
  { code: 'SV', flag: '🇸🇻', name: 'El Salvador', keywords: 'el salvador' },
  { code: 'GQ', flag: '🇬🇶', name: 'Equatorial Guinea', keywords: 'equatorial guinea' },
  { code: 'ER', flag: '🇪🇷', name: 'Eritrea', keywords: 'eritrea' },
  { code: 'EE', flag: '🇪🇪', name: 'Estonia', keywords: 'estonia estonian' },
  { code: 'SZ', flag: '🇸🇿', name: 'Eswatini', keywords: 'eswatini swaziland' },
  { code: 'ET', flag: '🇪🇹', name: 'Ethiopia', keywords: 'ethiopia ethiopian' },
  { code: 'FJ', flag: '🇫🇯', name: 'Fiji', keywords: 'fiji' },
  { code: 'FI', flag: '🇫🇮', name: 'Finland', keywords: 'finland finnish suomi' },
  { code: 'FR', flag: '🇫🇷', name: 'France', keywords: 'france french' },
  { code: 'PF', flag: '🇵🇫', name: 'French Polynesia', keywords: 'french polynesia tahiti' },
  { code: 'GA', flag: '🇬🇦', name: 'Gabon', keywords: 'gabon' },
  { code: 'GM', flag: '🇬🇲', name: 'Gambia', keywords: 'gambia' },
  { code: 'GE', flag: '🇬🇪', name: 'Georgia', keywords: 'georgia georgian sakartvelo' },
  { code: 'DE', flag: '🇩🇪', name: 'Germany', keywords: 'germany german deutschland' },
  { code: 'GH', flag: '🇬🇭', name: 'Ghana', keywords: 'ghana' },
  { code: 'GR', flag: '🇬🇷', name: 'Greece', keywords: 'greece greek hellas' },
  { code: 'GL', flag: '🇬🇱', name: 'Greenland', keywords: 'greenland kalaallit' },
  { code: 'GD', flag: '🇬🇩', name: 'Grenada', keywords: 'grenada' },
  { code: 'GU', flag: '🇬🇺', name: 'Guam', keywords: 'guam' },
  { code: 'GT', flag: '🇬🇹', name: 'Guatemala', keywords: 'guatemala' },
  { code: 'GN', flag: '🇬🇳', name: 'Guinea', keywords: 'guinea' },
  { code: 'GW', flag: '🇬🇼', name: 'Guinea-Bissau', keywords: 'guinea bissau' },
  { code: 'GY', flag: '🇬🇾', name: 'Guyana', keywords: 'guyana' },
  { code: 'HT', flag: '🇭🇹', name: 'Haiti', keywords: 'haiti' },
  { code: 'HN', flag: '🇭🇳', name: 'Honduras', keywords: 'honduras' },
  { code: 'HK', flag: '🇭🇰', name: 'Hong Kong', keywords: 'hong kong hk' },
  { code: 'HU', flag: '🇭🇺', name: 'Hungary', keywords: 'hungary hungarian magyar' },
  { code: 'IS', flag: '🇮🇸', name: 'Iceland', keywords: 'iceland icelandic' },
  { code: 'IN', flag: '🇮🇳', name: 'India', keywords: 'india indian bharat' },
  { code: 'ID', flag: '🇮🇩', name: 'Indonesia', keywords: 'indonesia indonesian' },
  { code: 'IR', flag: '🇮🇷', name: 'Iran', keywords: 'iran iranian persia' },
  { code: 'IQ', flag: '🇮🇶', name: 'Iraq', keywords: 'iraq iraqi' },
  { code: 'IE', flag: '🇮🇪', name: 'Ireland', keywords: 'ireland irish eire' },
  { code: 'IL', flag: '🇮🇱', name: 'Israel', keywords: 'israel israeli' },
  { code: 'IT', flag: '🇮🇹', name: 'Italy', keywords: 'italy italian italia' },
  { code: 'JM', flag: '🇯🇲', name: 'Jamaica', keywords: 'jamaica' },
  { code: 'JP', flag: '🇯🇵', name: 'Japan', keywords: 'japan japanese nippon' },
  { code: 'JO', flag: '🇯🇴', name: 'Jordan', keywords: 'jordan jordanian' },
  { code: 'KZ', flag: '🇰🇿', name: 'Kazakhstan', keywords: 'kazakhstan' },
  { code: 'KE', flag: '🇰🇪', name: 'Kenya', keywords: 'kenya kenyan' },
  { code: 'KI', flag: '🇰🇮', name: 'Kiribati', keywords: 'kiribati' },
  { code: 'KP', flag: '🇰🇵', name: 'North Korea', keywords: 'north korea dprk' },
  { code: 'KR', flag: '🇰🇷', name: 'South Korea', keywords: 'south korea korea rok' },
  { code: 'KW', flag: '🇰🇼', name: 'Kuwait', keywords: 'kuwait' },
  { code: 'KG', flag: '🇰🇬', name: 'Kyrgyzstan', keywords: 'kyrgyzstan' },
  { code: 'LA', flag: '🇱🇦', name: 'Laos', keywords: 'laos lao' },
  { code: 'LV', flag: '🇱🇻', name: 'Latvia', keywords: 'latvia latvian' },
  { code: 'LB', flag: '🇱🇧', name: 'Lebanon', keywords: 'lebanon lebanese' },
  { code: 'LS', flag: '🇱🇸', name: 'Lesotho', keywords: 'lesotho' },
  { code: 'LR', flag: '🇱🇷', name: 'Liberia', keywords: 'liberia' },
  { code: 'LY', flag: '🇱🇾', name: 'Libya', keywords: 'libya libyan' },
  { code: 'LI', flag: '🇱🇮', name: 'Liechtenstein', keywords: 'liechtenstein' },
  { code: 'LT', flag: '🇱🇹', name: 'Lithuania', keywords: 'lithuania lithuanian' },
  { code: 'LU', flag: '🇱🇺', name: 'Luxembourg', keywords: 'luxembourg' },
  { code: 'MO', flag: '🇲🇴', name: 'Macao', keywords: 'macao macau' },
  { code: 'MG', flag: '🇲🇬', name: 'Madagascar', keywords: 'madagascar' },
  { code: 'MW', flag: '🇲🇼', name: 'Malawi', keywords: 'malawi' },
  { code: 'MY', flag: '🇲🇾', name: 'Malaysia', keywords: 'malaysia malaysian' },
  { code: 'MV', flag: '🇲🇻', name: 'Maldives', keywords: 'maldives' },
  { code: 'ML', flag: '🇲🇱', name: 'Mali', keywords: 'mali' },
  { code: 'MT', flag: '🇲🇹', name: 'Malta', keywords: 'malta maltese' },
  { code: 'MH', flag: '🇲🇭', name: 'Marshall Islands', keywords: 'marshall islands' },
  { code: 'MR', flag: '🇲🇷', name: 'Mauritania', keywords: 'mauritania' },
  { code: 'MU', flag: '🇲🇺', name: 'Mauritius', keywords: 'mauritius' },
  { code: 'MX', flag: '🇲🇽', name: 'Mexico', keywords: 'mexico mexican' },
  { code: 'FM', flag: '🇫🇲', name: 'Micronesia', keywords: 'micronesia' },
  { code: 'MD', flag: '🇲🇩', name: 'Moldova', keywords: 'moldova moldovan' },
  { code: 'MC', flag: '🇲🇨', name: 'Monaco', keywords: 'monaco' },
  { code: 'MN', flag: '🇲🇳', name: 'Mongolia', keywords: 'mongolia mongolian' },
  { code: 'ME', flag: '🇲🇪', name: 'Montenegro', keywords: 'montenegro' },
  { code: 'MS', flag: '🇲🇸', name: 'Montserrat', keywords: 'montserrat' },
  { code: 'MA', flag: '🇲🇦', name: 'Morocco', keywords: 'morocco moroccan maroc' },
  { code: 'MZ', flag: '🇲🇿', name: 'Mozambique', keywords: 'mozambique' },
  { code: 'MM', flag: '🇲🇲', name: 'Myanmar', keywords: 'myanmar burma' },
  { code: 'NA', flag: '🇳🇦', name: 'Namibia', keywords: 'namibia' },
  { code: 'NR', flag: '🇳🇷', name: 'Nauru', keywords: 'nauru' },
  { code: 'NP', flag: '🇳🇵', name: 'Nepal', keywords: 'nepal nepali' },
  { code: 'NL', flag: '🇳🇱', name: 'Netherlands', keywords: 'netherlands dutch holland' },
  { code: 'NC', flag: '🇳🇨', name: 'New Caledonia', keywords: 'new caledonia' },
  { code: 'NZ', flag: '🇳🇿', name: 'New Zealand', keywords: 'new zealand kiwi aotearoa' },
  { code: 'NI', flag: '🇳🇮', name: 'Nicaragua', keywords: 'nicaragua' },
  { code: 'NE', flag: '🇳🇪', name: 'Niger', keywords: 'niger' },
  { code: 'NG', flag: '🇳🇬', name: 'Nigeria', keywords: 'nigeria nigerian' },
  { code: 'NU', flag: '🇳🇺', name: 'Niue', keywords: 'niue' },
  { code: 'MK', flag: '🇲🇰', name: 'North Macedonia', keywords: 'north macedonia macedonia' },
  { code: 'NO', flag: '🇳🇴', name: 'Norway', keywords: 'norway norwegian norge' },
  { code: 'OM', flag: '🇴🇲', name: 'Oman', keywords: 'oman' },
  { code: 'PK', flag: '🇵🇰', name: 'Pakistan', keywords: 'pakistan pakistani' },
  { code: 'PW', flag: '🇵🇼', name: 'Palau', keywords: 'palau' },
  { code: 'PS', flag: '🇵🇸', name: 'Palestine', keywords: 'palestine palestinian' },
  { code: 'PA', flag: '🇵🇦', name: 'Panama', keywords: 'panama' },
  { code: 'PG', flag: '🇵🇬', name: 'Papua New Guinea', keywords: 'papua new guinea' },
  { code: 'PY', flag: '🇵🇾', name: 'Paraguay', keywords: 'paraguay' },
  { code: 'PE', flag: '🇵🇪', name: 'Peru', keywords: 'peru peruvian' },
  { code: 'PH', flag: '🇵🇭', name: 'Philippines', keywords: 'philippines pinoy filipino' },
  { code: 'PL', flag: '🇵🇱', name: 'Poland', keywords: 'poland polish polska' },
  { code: 'PT', flag: '🇵🇹', name: 'Portugal', keywords: 'portugal portuguese' },
  { code: 'PR', flag: '🇵🇷', name: 'Puerto Rico', keywords: 'puerto rico' },
  { code: 'QA', flag: '🇶🇦', name: 'Qatar', keywords: 'qatar qatari' },
  { code: 'RE', flag: '🇷🇪', name: 'Réunion', keywords: 'reunion reunion' },
  { code: 'RO', flag: '🇷🇴', name: 'Romania', keywords: 'romania romanian' },
  { code: 'RU', flag: '🇷🇺', name: 'Russia', keywords: 'russia russian federation' },
  { code: 'RW', flag: '🇷🇼', name: 'Rwanda', keywords: 'rwanda' },
  { code: 'WS', flag: '🇼🇸', name: 'Samoa', keywords: 'samoa' },
  { code: 'SM', flag: '🇸🇲', name: 'San Marino', keywords: 'san marino' },
  { code: 'ST', flag: '🇸🇹', name: 'São Tomé and Príncipe', keywords: 'sao tome principe' },
  { code: 'SA', flag: '🇸🇦', name: 'Saudi Arabia', keywords: 'saudi arabia ksa' },
  { code: 'SN', flag: '🇸🇳', name: 'Senegal', keywords: 'senegal' },
  { code: 'RS', flag: '🇷🇸', name: 'Serbia', keywords: 'serbia serbian srbija' },
  { code: 'SC', flag: '🇸🇨', name: 'Seychelles', keywords: 'seychelles' },
  { code: 'SL', flag: '🇸🇱', name: 'Sierra Leone', keywords: 'sierra leone' },
  { code: 'SG', flag: '🇸🇬', name: 'Singapore', keywords: 'singapore' },
  { code: 'SK', flag: '🇸🇰', name: 'Slovakia', keywords: 'slovakia slovak' },
  { code: 'SI', flag: '🇸🇮', name: 'Slovenia', keywords: 'slovenia slovenian' },
  { code: 'SB', flag: '🇸🇧', name: 'Solomon Islands', keywords: 'solomon islands' },
  { code: 'SO', flag: '🇸🇴', name: 'Somalia', keywords: 'somalia' },
  { code: 'ZA', flag: '🇿🇦', name: 'South Africa', keywords: 'south africa rsa' },
  { code: 'SS', flag: '🇸🇸', name: 'South Sudan', keywords: 'south sudan' },
  { code: 'ES', flag: '🇪🇸', name: 'Spain', keywords: 'spain spanish espana' },
  { code: 'LK', flag: '🇱🇰', name: 'Sri Lanka', keywords: 'sri lanka' },
  { code: 'SD', flag: '🇸🇩', name: 'Sudan', keywords: 'sudan sudanese' },
  { code: 'SR', flag: '🇸🇷', name: 'Suriname', keywords: 'suriname' },
  { code: 'SE', flag: '🇸🇪', name: 'Sweden', keywords: 'sweden swedish sverige' },
  { code: 'CH', flag: '🇨🇭', name: 'Switzerland', keywords: 'switzerland swiss' },
  { code: 'SY', flag: '🇸🇾', name: 'Syria', keywords: 'syria syrian' },
  { code: 'TW', flag: '🇹🇼', name: 'Taiwan', keywords: 'taiwan taiwanese' },
  { code: 'TJ', flag: '🇹🇯', name: 'Tajikistan', keywords: 'tajikistan' },
  { code: 'TZ', flag: '🇹🇿', name: 'Tanzania', keywords: 'tanzania' },
  { code: 'TH', flag: '🇹🇭', name: 'Thailand', keywords: 'thailand thai' },
  { code: 'TL', flag: '🇹🇱', name: 'Timor-Leste', keywords: 'timor leste east timor' },
  { code: 'TG', flag: '🇹🇬', name: 'Togo', keywords: 'togo' },
  { code: 'TO', flag: '🇹🇴', name: 'Tonga', keywords: 'tonga' },
  { code: 'TT', flag: '🇹🇹', name: 'Trinidad and Tobago', keywords: 'trinidad tobago' },
  { code: 'TN', flag: '🇹🇳', name: 'Tunisia', keywords: 'tunisia tunisian' },
  { code: 'TR', flag: '🇹🇷', name: 'Turkey', keywords: 'turkey turkish turkiye' },
  { code: 'TM', flag: '🇹🇲', name: 'Turkmenistan', keywords: 'turkmenistan' },
  { code: 'TC', flag: '🇹🇨', name: 'Turks and Caicos Islands', keywords: 'turks caicos' },
  { code: 'UG', flag: '🇺🇬', name: 'Uganda', keywords: 'uganda' },
  { code: 'UA', flag: '🇺🇦', name: 'Ukraine', keywords: 'ukraine ukrainian' },
  { code: 'AE', flag: '🇦🇪', name: 'United Arab Emirates', keywords: 'united arab emirates uae emirates dubai' },
  { code: 'GB', flag: '🇬🇧', name: 'United Kingdom', keywords: 'united kingdom uk britain british england' },
  { code: 'US', flag: '🇺🇸', name: 'United States', keywords: 'united states usa america' },
  { code: 'UY', flag: '🇺🇾', name: 'Uruguay', keywords: 'uruguay' },
  { code: 'UZ', flag: '🇺🇿', name: 'Uzbekistan', keywords: 'uzbekistan' },
  { code: 'VU', flag: '🇻🇺', name: 'Vanuatu', keywords: 'vanuatu' },
  { code: 'VA', flag: '🇻🇦', name: 'Vatican City', keywords: 'vatican city holy see' },
  { code: 'VE', flag: '🇻🇪', name: 'Venezuela', keywords: 'venezuela' },
  { code: 'VN', flag: '🇻🇳', name: 'Vietnam', keywords: 'vietnam vietnamese viet nam' },
  { code: 'VG', flag: '🇻🇬', name: 'British Virgin Islands', keywords: 'british virgin islands' },
  { code: 'VI', flag: '🇻🇮', name: 'U.S. Virgin Islands', keywords: 'us virgin islands' },
  { code: 'YE', flag: '🇾🇪', name: 'Yemen', keywords: 'yemen yemeni' },
  { code: 'ZM', flag: '🇿🇲', name: 'Zambia', keywords: 'zambia' },
  { code: 'ZW', flag: '🇿🇼', name: 'Zimbabwe', keywords: 'zimbabwe' },
];

// countryByCode resolves an ISO-3166 alpha-2 code (the persisted value)
// to its full row. Returns undefined when the code is empty or unknown.
export function countryByCode(code: string): CountryRow | undefined {
  if (!code) return undefined;
  return COUNTRIES.find((c) => c.code === code.toUpperCase());
}
