-- 038_instance_suspension.sql: add suspension fields to instances table
--
-- This migration is handled entirely in Go (db.go:RunMigrations) via guardedAddColumns
-- for idempotent column additions on SQLite/MySQL. The columns added are:
--   suspended          INTEGER NOT NULL DEFAULT 0
--   suspended_until    TIMESTAMP
--   suspension_count   INTEGER NOT NULL DEFAULT 0
--   suspension_history TEXT
-- And index: CREATE INDEX IF NOT EXISTS idx_instances_suspended ON instances(suspended)
--
-- The Postgres version uses native ADD COLUMN IF NOT EXISTS and is also
-- guarded by the same Go code for consistency.