package handlers

import (
	"log"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"
	"time"

	"github.com/example/kspanel/internal/repository"
)

// ddosScriptTemplate is the shell script template for the emergency DDoS
// port switch. It runs independently of the panel process (like
// reinstallScriptTemplate): it stops the running panel and starts it on
// the DDoS alternate port as `kspanel launch --port <alt> --type ddos` —
// the ddos launch type means that port is NOT saved in the database as
// the last port, so the next normal start comes back on the original
// port. If the alternate port fails to come up the script rolls back to
// a normal start on the original port.
const ddosScriptTemplate = `#!/bin/bash
# KS Panel DDoS Emergency Port Switch Script
# Generated by panel on {{.GeneratedAt}}
# Panel binary: {{.BinaryPath}}
# Current (primary) port: {{.PrimaryPort}}
# DDoS alternate port: {{.AltPort}}
#
# What it does:
#   1. Stops the running panel (HTTP stop on both known ports, then pkill).
#   2. Starts the panel on the ALTERNATE port with --type ddos, so the
#      alternate port is NOT saved in the DB as the last port — the next
#      normal start returns to the primary port above.
#   3. If the panel does not come up on the alternate port, rolls back to a
#      normal start on the primary port.

# We deliberately do NOT enable set -e here: this script's whole point is
# to recover from failure (alt port busy, slow migrations, ...) and set -e
# would abort the cleanup-on-exit trap mid-recovery. Every individual step
# has its own error check so failures are surfaced loudly without the
# shell killing us before we can roll back.
set -u
set -o pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $*"; }
log_ok() { echo -e "${GREEN}[OK]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_err() { echo -e "${RED}[ERR]${NC} $*"; }

# Configuration
BINARY_PATH="{{.BinaryPath}}"
PANEL_LOG="${BINARY_PATH%/*}/panel.log"
PRIMARY_PORT="${PRIMARY_PORT:-{{.PrimaryPort}}}"
ALT_PORT="${ALT_PORT:-{{.AltPort}}}"
MAX_WAIT_START=90
POLL_INTERVAL=2

# Track whether the alternate-port start succeeded so the EXIT trap knows
# whether a rollback is needed.
STARTED_ALT=false

if [[ "$ALT_PORT" == "$PRIMARY_PORT" ]]; then
    log_err "Alternate port equals primary port ($PRIMARY_PORT) — nothing to switch. Set DDOSAltPort in the Security settings first."
    # Nothing was stopped yet, so the rollback trap must NOT fire here.
    trap - EXIT
    exit 1
fi

# start_panel_at bin port mode: spawn the binary detached (setsid, its own
# session leader — see reinstall.sh for the SIGHUP rationale) on the given
# port. mode="ddos" appends --type ddos so the panel treats the port as a
# temporary escape port and does NOT save it in the DB as the last port;
# mode="normal" starts normally and lets launch persist the port as usual.
start_panel_at() {
    local bin="$1"
    local port="$2"
    local mode="$3"
    cd "${bin%/*}"
    if [[ "$mode" == "ddos" ]]; then
        setsid nohup "$bin" launch --port "$port" --type ddos >> "$PANEL_LOG" 2>&1 < /dev/null &
    else
        setsid nohup "$bin" launch --port "$port" >> "$PANEL_LOG" 2>&1 < /dev/null &
    fi
    echo $!
}

# wait_for_healthy port: poll http://127.0.0.1:$1/health until it answers
# or the timeout elapses. Echoes ok or fail. Progress lines go to STDERR
# because callers capture stdout with $().
wait_for_healthy() {
    local port="$1"
    local elapsed=0
    while [[ $elapsed -lt $MAX_WAIT_START ]]; do
        if curl -sf "http://127.0.0.1:${port}/health" >/dev/null 2>&1; then
            echo "ok"
            return 0
        fi
        sleep $POLL_INTERVAL
        elapsed=$((elapsed + POLL_INTERVAL))
        log_info "Waiting for :${port}... (${elapsed}s elapsed)" >&2
    done
    echo "fail"
    return 1
}

# wait_port_free port: belt-and-braces wait until nothing accepts on $1
# anymore (pkill -9 doesn't release a TIME_WAIT socket instantly).
wait_port_free() {
    local port="$1"
    local waited=0
    while [[ $waited -lt 15 ]]; do
        if ! (echo > "/dev/tcp/127.0.0.1/${port}") 2>/dev/null; then
            return 0
        fi
        log_info "Port $port still bound, waiting..."
        sleep 2
        waited=$((waited + 2))
    done
}

# stop_panel: graceful HTTP stop on both known ports (the panel may
# currently be on either one), then the pkill ladder as fallback.
stop_panel() {
    local p
    for p in "$PRIMARY_PORT" "$ALT_PORT"; do
        if "${BINARY_PATH}" stop --port "${p}" >/dev/null 2>&1; then
            log_ok "Panel stopped gracefully via CLI (port $p)"
            return 0
        fi
    done
    log_warn "CLI stop failed, falling back to pkill..."
    pkill -f "^${BINARY_PATH} launch" 2>/dev/null || true
    pkill -f "$(basename "${BINARY_PATH}") launch" 2>/dev/null || true
    pkill -f "${BINARY_PATH}" 2>/dev/null || true
    sleep 2
    if pgrep -f "${BINARY_PATH}" >/dev/null 2>&1; then
        log_warn "Panel still running, forcing kill..."
        pkill -9 -f "${BINARY_PATH}" 2>/dev/null || true
        sleep 1
    fi
}

cleanup_on_exit() {
    local exit_code=$?
    if [[ $exit_code -ne 0 ]]; then
        log_err "Script exited with code $exit_code"
    fi

    # Alternate port didn't come up → put the panel back on the primary
    # port with a NORMAL start (persist allowed; it is the original port
    # anyway), so the box is never left without a panel.
    if [[ "$STARTED_ALT" == "false" && "$exit_code" -ne 0 ]]; then
        log_warn "Rolling back: starting panel on primary port $PRIMARY_PORT..."
        wait_port_free "$ALT_PORT"
        local pid
        pid=$(start_panel_at "$BINARY_PATH" "$PRIMARY_PORT" "normal") || true
        if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
            log_ok "Panel restarted on primary port $PRIMARY_PORT"
        else
            log_err "Failed to restart panel on primary port — check $PANEL_LOG"
        fi
    fi
}

trap cleanup_on_exit EXIT

log_info "=== KS Panel DDoS Port Switch Started ==="
log_info "Binary: $BINARY_PATH"
log_info "Primary port: $PRIMARY_PORT"
log_info "Alternate port: $ALT_PORT (temporary --type ddos — will NOT be saved as last port)"

# 1. Stop the current panel and wait for the sockets to clear.
log_info "Stopping current panel..."
stop_panel
wait_port_free "$PRIMARY_PORT"
wait_port_free "$ALT_PORT"
log_ok "Panel stopped"

# 2. Start the panel on the alternate port with --type ddos
# so the DB keeps the original port as the last port.
log_info "Starting panel on alternate port $ALT_PORT (temporary)..."
PANEL_PID=$(start_panel_at "$BINARY_PATH" "$ALT_PORT" "ddos") || {
    log_err "Could not spawn panel on alternate port"
    exit 1
}
log_info "Panel started with PID: $PANEL_PID"

# Brief grace window so a crash-on-boot surfaces via kill -0 before the
# health polling starts (same convention as reinstall.sh).
sleep 3
if ! kill -0 "$PANEL_PID" 2>/dev/null; then
    log_err "Panel process exited within 3s of launch — check $PANEL_LOG"
    exit 1
fi

# 3. Wait for the panel to become healthy on the alternate port.
log_info "Waiting for panel on :$ALT_PORT (max ${MAX_WAIT_START}s)..."
if [[ "$(wait_for_healthy "$ALT_PORT")" == "ok" ]]; then
    STARTED_ALT=true
    log_ok "Panel is up on alternate port $ALT_PORT"
    log_ok "Saved last port unchanged — next normal start returns to $PRIMARY_PORT"
    log_info "=== DDoS Port Switch Completed Successfully ==="
    # Clear the EXIT trap so cleanup doesn't treat success as failure.
    trap - EXIT
    exit 0
fi

log_err "Panel did not become healthy on :$ALT_PORT within ${MAX_WAIT_START}s"
exit 1
`

// ddosScriptData is the payload baked into ddosScriptTemplate.
type ddosScriptData struct {
	GeneratedAt string
	BinaryPath  string
	PrimaryPort string
	AltPort     string
}

// ddosAltPort resolves the configured DDoS alternate port from the
// security settings KV (the same value the runtime port switcher reads).
// If the DB cannot be opened we fall back to the documented default
// (5050, mirroring SecurityRepository's defaultDDOSAltPort) instead of
// blocking an emergency tool on a transient DB hiccup — same trade-off
// effectivePanelPort makes for the primary port.
func ddosAltPort() string {
	const fallback = "5050"
	con, err := repository.OpenDB()
	if err != nil {
		return fallback
	}
	defer con.Close()
	if p := repository.NewSecurityRepository(con).GetConfig().DDOSAltPort; p >= 1 && p <= 65535 {
		return strconv.FormatInt(p, 10)
	}
	return fallback
}

// resolveDDOSBinaryPath mirrors the executable resolution the reinstall
// handlers perform: os.Executable with symlinks resolved so the script
// keeps working after an update swaps the binary path.
func resolveDDOSBinaryPath() (string, error) {
	exe, err := os.Executable()
	if err != nil {
		return "", err
	}
	if resolved, rerr := filepath.EvalSymlinks(exe); rerr == nil {
		exe = resolved
	}
	return exe, nil
}

// buildDDOSScript renders ddosScriptTemplate with the live values.
func buildDDOSScript() (string, string, error) {
	exe, err := resolveDDOSBinaryPath()
	if err != nil {
		return "", "", err
	}
	data := ddosScriptData{
		GeneratedAt: time.Now().UTC().Format(time.RFC3339),
		BinaryPath:  exe,
		PrimaryPort: effectivePanelPort(),
		AltPort:     ddosAltPort(),
	}
	tmpl, err := template.New("ddos-switch").Parse(ddosScriptTemplate)
	if err != nil {
		return "", "", err
	}
	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", "", err
	}
	return buf.String(), filepath.Join(filepath.Dir(exe), "ddos.sh"), nil
}

// DDOSScriptHandler serves GET /api/security/ddos/script: generates and
// returns the standalone ddos.sh script (download), mirroring
// ReinstallScriptHandler.
func DDOSScriptHandler(w http.ResponseWriter, r *http.Request) {
	script, _, err := buildDDOSScript()
	if err != nil {
		http.Error(w, "cannot generate ddos script: "+err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/x-sh")
	w.Header().Set("Content-Disposition", "attachment; filename=\"ddos.sh\"")

	if _, werr := w.Write([]byte(script)); werr != nil {
		log.Printf("ddos script write error: %v", werr)
	}
}

// ddosBackgroundResponse is the POST /api/security/ddos/background payload.
type ddosBackgroundResponse struct {
	OK      bool   `json:"ok"`
	Message string `json:"message"`
	Script  string `json:"script_path"`
}

// DDOSBackgroundHandler writes ddos.sh next to the panel binary and runs
// it detached. The script stops the panel and restarts it on the DDoS
// alternate port without saving that port; the HTTP response returns
// immediately while the switch happens in the background, mirroring
// ReinstallBackgroundHandler.
func DDOSBackgroundHandler(w http.ResponseWriter, r *http.Request) {
	script, scriptPath, err := buildDDOSScript()
	if err != nil {
		http.Error(w, "cannot generate ddos script: "+err.Error(), http.StatusInternalServerError)
		return
	}

	if err := os.WriteFile(scriptPath, []byte(script), 0o755); err != nil {
		http.Error(w, "failed to write ddos script: "+err.Error(), http.StatusInternalServerError)
		return
	}

	go func() {
		cmd := exec.Command("bash", scriptPath)
		cmd.Dir = filepath.Dir(scriptPath)
		cmd.Stdout = nil
		cmd.Stderr = nil
		cmd.Env = os.Environ()
		cmd.SysProcAttr = setDetachSysProcAttr()
		if err := cmd.Start(); err != nil {
			log.Printf("ddos background script start failed: %v", err)
			return
		}
		if cmd.Process != nil {
			_ = cmd.Process.Release()
		}
	}()

	writeJSON(w, ddosBackgroundResponse{
		OK:      true,
		Message: "ddos.sh started in background. The panel will stop and come back on the alternate port; the saved last port stays unchanged.",
		Script:  scriptPath,
	})
}
